[build]
target    = "xtensa-esp32s3-none-elf"
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3"

[unstable]
build-std = ["alloc", "core"]
